#!/bin/bash

function StartHomeAssistant {
  if test -f ".devcontainer/configuration.yaml"; then
    echo "Copy configuration.yaml"
    cp -f .devcontainer/configuration.yaml /config || echo ".devcontainer/configuration.yaml are missing"
  fi

  if test -f ".devcontainer/ui-lovelace.yaml"; then
    echo "Copy ui-lovelace.yaml"
    cp -f .devcontainer/ui-lovelace.yaml /config || echo ""
  fi

  if test -d "custom_components"; then
    echo "Symlink the custom component directory"

    if test -d "custom_components"; then
      rm -R /config/custom_components
    fi

    ln -sf "$(GetWorkspaceName)custom_components/" /config/custom_components || echo "Could not copy the custom_component" exit 1
  elif  test -f "__init__.py"; then
    echo "Having the component in the root are currently not supported"
  fi

  echo "Start Home Assistant"
  if ! [ -x "$(command -v hass)" ]; then
    echo "Home Assistant is not installed, running installation."
    UpdgradeHomeAssistantDev
  fi
  hass -c /config
}

function GetWorkspaceName {
  echo "$(find /workspaces -mindepth 1 -maxdepth 1 -type d)/"
}