#!/bin/bash

rm /usr/bin/cc
rm -r /usr/share/cc

ln -sf /workspaces/container/rootfs/common/etc/bash_completion.d/cc_completion /etc/bash_completion.d/cc_completion
ln -sf /workspaces/container/rootfs/common/root/.bashrc /root/.bashrc
ln -sf /workspaces/container/rootfs/common/usr/bin/dc /usr/bin/dc
ln -sf /workspaces/container/rootfs/common/usr/share/cc /usr/share/cc
ln -sf /workspaces/container/rootfs/common/usr/bin/cc /usr/bin/cc
python3 -m pip install ruamel.yaml