#!/bin/bash


curl -L -s https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-"${ELASTIC_VERSION}"-linux-x86_64.tar.gz | tar xzf - -C /usr/local
curl -L -s https://artifacts.elastic.co/downloads/kibana/kibana-oss-"${ELASTIC_VERSION}"-linux-x86_64.tar.gz | tar xzf - -C /usr/local

cp --verbose -R /usr/local/elasticsearch/* /usr/local/elasticsearch-"${ELASTIC_VERSION}"/
rm -R /usr/local/elasticsearch
mv /usr/local/elasticsearch-"${ELASTIC_VERSION}" /usr/local/elasticsearch

cp --verbose -R /usr/local/kibana/* /usr/local/kibana-"${ELASTIC_VERSION}"-linux-x86_64/
rm -R /usr/local/kibana
mv /usr/local/kibana-"${ELASTIC_VERSION}"-linux-x86_64 /usr/local/kibana

# fix node installation (https://github.com/elastic/kibana/issues/17015)
rm -rf /usr/local/kibana/node
mkdir -p /usr/local/kibana/node/bin
ln -s /usr/bin/node /usr/local/kibana/node/bin/node

# Fix for Kibana issue with node

sed -i 's/--max-http-header-size=65536//g' /usr/local/kibana/bin/kibana
sed -i 's/!isVersionValid/isVersionValid/g' /usr/local/kibana/src/setup_node_env/node_version_validator.js