#!/bin/bash

function GetWorkspaceDirectory() {
    echo $(GetWorkspaceName)
}

function GetWorkspaceName {
  echo "$(find /workspaces -mindepth 2 -maxdepth 2 -type d -name custom_components -exec dirname {} \;)/"
}
