name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test buildx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build images
        run: docker buildx --help
