name: TEST

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: TEST
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Initialize git
        uses: home-assistant/actions/helpers/git-init@master
        with:
          name: Ludeeus
          email: hi@ludeeus

      - name: GH CLI
        run: |
          echo "test" > test
          git add .
          git commit -m "test"
          export GITHUB_TOKEN="${{ secrets.GHCR_TOKEN }}"
          gh pr create --title "test" --body "test"